name: MvcApiClient
targets:
  MvcApiClient:
    type: framework
    platform: iOS
    deploymentTarget: "10.0"
    sources: [MvcApiClient]
    info:
      path: ./Info.plist
      version: 3.0.8
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    
