name: MetaSVMvcClient
targets:
  MetaSVMvcClient:
    type: framework
    platform: iOS
    deploymentTarget: "10.0"
    sources: [MetaSVMvcClient]
    info:
      path: ./Info.plist
      version: 2.2.0
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    
