//
// AddressTx.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Transaction history of the address. */
public struct AddressTx: Codable {

    /** Paging flag */
    public var flag: String?
    /** The address of the record */
    public var address: String?
    /** timestamp of the tx */
    public var time: Int64?
    /** Block Height of the tx, -1 if not confirmed */
    public var height: Int64?
    /** total income of the address from this tx */
    public var income: Int64?
    /** total outcome of the address from this tx */
    public var outcome: Int64?
    /** txid of this record */
    public var txid: String?

    public init(flag: String? = nil, address: String? = nil, time: Int64? = nil, height: Int64? = nil, income: Int64? = nil, outcome: Int64? = nil, txid: String? = nil) {
        self.flag = flag
        self.address = address
        self.time = time
        self.height = height
        self.income = income
        self.outcome = outcome
        self.txid = txid
    }

}

