//
// AddressBalance.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The current balance for a particular address */
public struct AddressBalance: Codable {

    /** current address */
    public var address: String?
    /** confirmed balance */
    public var confirmed: Int64?
    /** unconfirmed balance */
    public var unconfirmed: Int64?

    public init(address: String? = nil, confirmed: Int64? = nil, unconfirmed: Int64? = nil) {
        self.address = address
        self.confirmed = confirmed
        self.unconfirmed = unconfirmed
    }

}

