//
// BatchBroadcastResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Batch broadcast result */
public struct BatchBroadcastResult: Codable {

    /** Already known transactions detected during processing (if there are any) */
    public var known: [String]?
    /** Transactions accepted by the mempool and then evicted due to insufficient fee (if there are any) */
    public var evicted: [String]?
    /** Transactions that failed to be accepted by the mempool (if there are any) */
    public var invalid: [InvalidBroadCast]?

    public init(known: [String]? = nil, evicted: [String]? = nil, invalid: [InvalidBroadCast]? = nil) {
        self.known = known
        self.evicted = evicted
        self.invalid = invalid
    }

}

