//
// BlockHeaderPage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** block header saved by partition page */
public struct BlockHeaderPage: Codable {

    /** Block height. */
    public var height: Int64?
    /** Block hash. */
    public var blockHash: String?
    /** Block timestamp. */
    public var timestamp: Int64?
    /** current median time */
    public var medianTime: Int64?
    /** Miner total rewards, including miner fee. */
    public var reward: Int64?
    /** Guessed miner name. */
    public var miner: String?
    /** Total txs count included in the block. */
    public var txCount: Int?
    /** Size of the block */
    public var size: Int64?

    public init(height: Int64? = nil, blockHash: String? = nil, timestamp: Int64? = nil, medianTime: Int64? = nil, reward: Int64? = nil, miner: String? = nil, txCount: Int? = nil, size: Int64? = nil) {
        self.height = height
        self.blockHash = blockHash
        self.timestamp = timestamp
        self.medianTime = medianTime
        self.reward = reward
        self.miner = miner
        self.txCount = txCount
        self.size = size
    }

}

