//
// BlockchainInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct BlockchainInfo: Codable {

    /** mainnet or testnet */
    public var chain: String?
    /** current block count */
    public var blocks: Int?
    /** current block header count */
    public var headers: Int?
    /** current highest blockhash */
    public var bestBlockHash: String?
    /** decimal string for current difficulty */
    public var difficulty: String?
    /** current median time */
    public var medianTime: Int64?
    /** current pow */
    public var chainwork: String?
    /** estimated current network hash rate. */
    public var networkHashPerSecond: String?
    /** current mempool transaction count. */
    public var mempoolTxCount: Int?
    /** current mempool usage. */
    public var mempoolUsage: Int64?
    /** next estimated block size. */
    public var estimatedBlockSize: Int64?

    public init(chain: String? = nil, blocks: Int? = nil, headers: Int? = nil, bestBlockHash: String? = nil, difficulty: String? = nil, medianTime: Int64? = nil, chainwork: String? = nil, networkHashPerSecond: String? = nil, mempoolTxCount: Int? = nil, mempoolUsage: Int64? = nil, estimatedBlockSize: Int64? = nil) {
        self.chain = chain
        self.blocks = blocks
        self.headers = headers
        self.bestBlockHash = bestBlockHash
        self.difficulty = difficulty
        self.medianTime = medianTime
        self.chainwork = chainwork
        self.networkHashPerSecond = networkHashPerSecond
        self.mempoolTxCount = mempoolTxCount
        self.mempoolUsage = mempoolUsage
        self.estimatedBlockSize = estimatedBlockSize
    }

}

