//
// BroadcastResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Broadcast result */
public struct BroadcastResult: Codable {

    /** return txid if broadcast success */
    public var txid: String?
    /** return messages if broadcast failed */
    public var message: String?

    public init(txid: String? = nil, message: String? = nil) {
        self.txid = txid
        self.message = message
    }

}

