//
// ClientPubkeyRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Request object to register(or delete) a new client public key. */
public struct ClientPubkeyRequest: Codable {

    /** The hex format public key to register. (i.e. 02fd17dd0c52e54e5eed4ebe1e75df5e48df422f81c26520d44380bef1691fdd98) */
    public var pubkey: String?

    public init(pubkey: String? = nil) {
        self.pubkey = pubkey
    }

}

