//
// ContractFtUtxo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Contract fungible token Utxo belongs to the specified address */
public struct ContractFtUtxo: Codable {

    /** Address string of this utxo */
    public var address: String?
    /** Codehash of this utxo. */
    public var codeHash: String?
    /** Genesis of this utxo. */
    public var genesis: String?
    /** Name of the token. */
    public var name: String?
    /** Symbol of the token. */
    public var symbol: String?
    /** SensibleId of the token */
    public var sensibleId: String?
    /** The decimal position. */
    public var decimal: Int?
    /** Txid for this utxo. */
    public var txid: String?
    /** Output index for the Utxo. */
    public var txIndex: Int?
    /** Token value of the utxo(Irrelavant to satoshi value). */
    public var value: Int64?
    /** Token value of the utxo(In string format) */
    public var valueString: String?
    /** Mvc value of the utxo(Irrelavant to token value) */
    public var satoshi: Int64?
    /** Mvc value of the utxo(In string format) */
    public var satoshiString: String?
    /** The height of this utxo, -1 for unconfirmed utxo. */
    public var height: Int64?
    /** Flag used for paging */
    public var flag: String?

    public init(address: String? = nil, codeHash: String? = nil, genesis: String? = nil, name: String? = nil, symbol: String? = nil, sensibleId: String? = nil, decimal: Int? = nil, txid: String? = nil, txIndex: Int? = nil, value: Int64? = nil, valueString: String? = nil, satoshi: Int64? = nil, satoshiString: String? = nil, height: Int64? = nil, flag: String? = nil) {
        self.address = address
        self.codeHash = codeHash
        self.genesis = genesis
        self.name = name
        self.symbol = symbol
        self.sensibleId = sensibleId
        self.decimal = decimal
        self.txid = txid
        self.txIndex = txIndex
        self.value = value
        self.valueString = valueString
        self.satoshi = satoshi
        self.satoshiString = satoshiString
        self.height = height
        self.flag = flag
    }

}

