//
// ContractFtBalance.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Contract fungible token balance */
public struct ContractFtBalance: Codable {

    /** Codehash of the token. */
    public var codeHash: String?
    /** Genesis of the token. */
    public var genesis: String?
    /** Name of the token. */
    public var name: String?
    /** Symbol of the token. */
    public var symbol: String?
    /** The decimal position. */
    public var decimal: Int?
    /** SensibleId of the token */
    public var sensibleId: String?
    /** Number of utxos for this token. */
    public var utxoCount: Int?
    /** Confirmed balance of the token. */
    public var confirmed: Int64?
    /** Confirmed balance of the token(In string format). */
    public var confirmedString: String?
    /** Unconfirmed balance of the token. */
    public var unconfirmed: Int64?
    /** Unconfirmed balance of the token(In string format). */
    public var unconfirmedString: String?

    public init(codeHash: String? = nil, genesis: String? = nil, name: String? = nil, symbol: String? = nil, decimal: Int? = nil, sensibleId: String? = nil, utxoCount: Int? = nil, confirmed: Int64? = nil, confirmedString: String? = nil, unconfirmed: Int64? = nil, unconfirmedString: String? = nil) {
        self.codeHash = codeHash
        self.genesis = genesis
        self.name = name
        self.symbol = symbol
        self.decimal = decimal
        self.sensibleId = sensibleId
        self.utxoCount = utxoCount
        self.confirmed = confirmed
        self.confirmedString = confirmedString
        self.unconfirmed = unconfirmed
        self.unconfirmedString = unconfirmedString
    }

}

