//
// InvalidBroadCast.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Invalid transactions detected during validation (if there are any) */
public struct InvalidBroadCast: Codable {

    /** return txid if broadcast success */
    public var txid: String?
    /** return messages if broadcast failed */
    public var rejectCode: Int?
    /** return messages if broadcast failed */
    public var rejectReason: String?
    /** return messages if broadcast failed */
    public var collideWith: [InvalidBroadcastCollide]?

    public init(txid: String? = nil, rejectCode: Int? = nil, rejectReason: String? = nil, collideWith: [InvalidBroadcastCollide]? = nil) {
        self.txid = txid
        self.rejectCode = rejectCode
        self.rejectReason = rejectReason
        self.collideWith = collideWith
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case txid
        case rejectCode = "reject_code"
        case rejectReason = "reject_reason"
        case collideWith
    }

}

