//
// InvalidBroadcastCollide.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** This field is only present in case of double spent transaction and contains transactions we collided with */
public struct InvalidBroadcastCollide: Codable {

    /** The transaction id */
    public var txid: String?
    /** Transaction size in bytes */
    public var size: Int?
    /** Whole transaction in hex */
    public var hex: String?

    public init(txid: String? = nil, size: Int? = nil, hex: String? = nil) {
        self.txid = txid
        self.size = size
        self.hex = hex
    }

}

