//
// ModelErrorResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Error response. */
public struct ModelErrorResponse: Codable {

    /** The reason for this error. */
    public var message: String?

    public init(message: String? = nil) {
        self.message = message
    }

}

