//
// TreasuryInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** current treasury utxo info */
public struct TreasuryInfo: Codable {

    /** current treasury utxo txid */
    public var txid: String?
    /** current treasury utxo index */
    public var index: Int?
    /** current treasury amount */
    public var amount: Int64?
    /** current treasury utxo height */
    public var height: Int64?
    /** current treasury utxo block hash */
    public var blockHash: String?
    /** current treasury utxo timestamp */
    public var timestamp: Int64?

    public init(txid: String? = nil, index: Int? = nil, amount: Int64? = nil, height: Int64? = nil, blockHash: String? = nil, timestamp: Int64? = nil) {
        self.txid = txid
        self.index = index
        self.amount = amount
        self.height = height
        self.blockHash = blockHash
        self.timestamp = timestamp
    }

}

