//
// TreasuryHistory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** treasury transaction history */
public struct TreasuryHistory: Codable {

    /** treasury transaction txid. */
    public var txid: String?
    /** treasury transaction spent outcome in satoshi. */
    public var outcome: Int64?
    /** treasury transaction timestamp. */
    public var timestamp: Int64?
    /** Reason for treasury transaction. */
    public var reason: String?
    /** Announcement link for treasury transaction. */
    public var announcementUrl: String?

    public init(txid: String? = nil, outcome: Int64? = nil, timestamp: Int64? = nil, reason: String? = nil, announcementUrl: String? = nil) {
        self.txid = txid
        self.outcome = outcome
        self.timestamp = timestamp
        self.reason = reason
        self.announcementUrl = announcementUrl
    }

}

