//
// TxDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Parsed tx info */
public struct TxDetail: Codable {

    public var txDetail: BlockTx?
    public var inputs: [TxInput]?
    public var outputs: [TxOutput]?

    public init(txDetail: BlockTx? = nil, inputs: [TxInput]? = nil, outputs: [TxOutput]? = nil) {
        self.txDetail = txDetail
        self.inputs = inputs
        self.outputs = outputs
    }

}

