//
// TxRaw.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Raw hex formatted Tx returned. */
public struct TxRaw: Codable {

    /** hex formatted raw tx. */
    public var hex: String?

    public init(hex: String? = nil) {
        self.hex = hex
    }

}

