//
// XpubAddress.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Address detail in the wallet */
public struct XpubAddress: Codable {

    /** xpub in the query */
    public var xpub: String?
    /** Address in the query */
    public var address: String?
    /** Address type, 0 for receive address, 1 for change address. path is {{addressType}}/{{addressIndex}} */
    public var addressType: Int?
    /** Address index. Address path in the xpub is {{addressType}}/{{addressIndex}} */
    public var addressIndex: Int?

    public init(xpub: String? = nil, address: String? = nil, addressType: Int? = nil, addressIndex: Int? = nil) {
        self.xpub = xpub
        self.address = address
        self.addressType = addressType
        self.addressIndex = addressIndex
    }

}

