//
// XpubBalance.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Registered Xpub balance including confirmed and unconfirmed */
public struct XpubBalance: Codable {

    /** confirmed balance */
    public var confirmed: Int64?
    /** unconfirmed balance */
    public var unconfirmed: Int64?

    public init(confirmed: Int64? = nil, unconfirmed: Int64? = nil) {
        self.confirmed = confirmed
        self.unconfirmed = unconfirmed
    }

}

