//
// AddressUtxo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Utxos by address(or addresses) order by height asc. */
public struct AddressUtxo: Codable {

    /** paging flag */
    public var flag: String?
    /** Address of the utxo */
    public var address: String?
    /** txid of the utxo */
    public var txid: String?
    /** output index in the tx */
    public var outIndex: Int?
    /** Value of the utxo */
    public var value: Int64?
    /** Height of the utxo, -1 if not confirmed */
    public var height: Int?

    public init(flag: String? = nil, address: String? = nil, txid: String? = nil, outIndex: Int? = nil, value: Int64? = nil, height: Int? = nil) {
        self.flag = flag
        self.address = address
        self.txid = txid
        self.outIndex = outIndex
        self.value = value
        self.height = height
    }

}

