//
// AsyncBroadcastResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Broadcast result */
public struct AsyncBroadcastResult: Codable {

    /** the txid of this tx */
    public var txid: String?
    /** the state of this tx, possible values PENDING, BROADCASTED, INVALID, UNKNOWN */
    public var state: String?
    /** return messages if broadcast failed */
    public var message: String?

    public init(txid: String? = nil, state: String? = nil, message: String? = nil) {
        self.txid = txid
        self.state = state
        self.message = message
    }

}

