//
// BlockchainInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct BlockchainInfo: Codable {

    /** mainnet or testnet */
    public var chain: String?
    /** current block count */
    public var blocks: Int?
    /** current block header count */
    public var headers: Int?
    /** current highest blockhash */
    public var bestBlockHash: String?
    /** decimal string for current difficulty */
    public var difficulty: String?
    /** current median time */
    public var medianTime: Int64?
    /** current pow */
    public var chainwork: String?

    public init(chain: String? = nil, blocks: Int? = nil, headers: Int? = nil, bestBlockHash: String? = nil, difficulty: String? = nil, medianTime: Int64? = nil, chainwork: String? = nil) {
        self.chain = chain
        self.blocks = blocks
        self.headers = headers
        self.bestBlockHash = bestBlockHash
        self.difficulty = difficulty
        self.medianTime = medianTime
        self.chainwork = chainwork
    }

}

