//
// ClientPubkeyResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Client public key result */
public struct ClientPubkeyResult: Codable {

    /** return pubkey if created successfully */
    public var pubkey: String?
    /** return messages if broadcast failed */
    public var message: String?

    public init(pubkey: String? = nil, message: String? = nil) {
        self.pubkey = pubkey
        self.message = message
    }

}

