//
// ContractUniqueUtxo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Contract unique Utxo indexed by codeHash and genesis. */
public struct ContractUniqueUtxo: Codable {

    /** Txid for this utxo. */
    public var txid: String?
    /** Output index for the Utxo. */
    public var txIndex: Int?
    /** Codehash of this utxo. */
    public var codeHash: String?
    /** Genesis of this utxo. */
    public var genesis: String?
    /** SensibleId of the token */
    public var sensibleId: String?
    /** The height of this utxo, -1 for unconfirmed utxo. */
    public var height: Int?
    /** The hex encoded customData */
    public var customData: String?
    /** Mvc value of the utxo(Irrelavant to token value) */
    public var satoshi: Int64?
    /** Mvc value of the utxo(In string format) */
    public var satoshiString: String?

    public init(txid: String? = nil, txIndex: Int? = nil, codeHash: String? = nil, genesis: String? = nil, sensibleId: String? = nil, height: Int? = nil, customData: String? = nil, satoshi: Int64? = nil, satoshiString: String? = nil) {
        self.txid = txid
        self.txIndex = txIndex
        self.codeHash = codeHash
        self.genesis = genesis
        self.sensibleId = sensibleId
        self.height = height
        self.customData = customData
        self.satoshi = satoshi
        self.satoshiString = satoshiString
    }

}

