//
// OutputInfoDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** spent status and value info of the output with detailed output script. */
public struct OutputInfoDetail: Codable {

    /** txid that this output is in. */
    public var txid: String?
    /** index of this output in the tx. */
    public var index: Int?
    /** output scrypt in hex format */
    public var script: String?
    /** parsed address of this output, empty for non standard. */
    public var address: String?
    /** value of this output */
    public var value: Int64?
    /** this output is spent or not, true if spent */
    public var spent: Bool?
    /** txid that spent this output */
    public var spentTxid: String?
    /** vin index of the spent tx */
    public var spentIndex: Int?
    /** height of the spent tx(-1 if unconfirmed, 0 if unspent) */
    public var spentHeight: Int?

    public init(txid: String? = nil, index: Int? = nil, script: String? = nil, address: String? = nil, value: Int64? = nil, spent: Bool? = nil, spentTxid: String? = nil, spentIndex: Int? = nil, spentHeight: Int? = nil) {
        self.txid = txid
        self.index = index
        self.script = script
        self.address = address
        self.value = value
        self.spent = spent
        self.spentTxid = spentTxid
        self.spentIndex = spentIndex
        self.spentHeight = spentHeight
    }

}

