//
// TxInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Parsed inputs from raw tx. Use output api to get value and spent info. */
public struct TxInput: Codable {

    /** Input index of the tx. */
    public var index: Int?
    /** The outpoint utxo txid that this input spent */
    public var utxoTxid: String?
    /** The outpoint utxo index that this input spent */
    public var utxoIndex: Int?
    /** Parsed address from pubkey(P2PKH input only). */
    public var address: String?
    /** satoshi value of this input. */
    public var value: Int64?
    /** The hex of the input script. */
    public var unlockScript: String?

    public init(index: Int? = nil, utxoTxid: String? = nil, utxoIndex: Int? = nil, address: String? = nil, value: Int64? = nil, unlockScript: String? = nil) {
        self.index = index
        self.utxoTxid = utxoTxid
        self.utxoIndex = utxoIndex
        self.address = address
        self.value = value
        self.unlockScript = unlockScript
    }

}

