//
// UtxoPickRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Request object to batch pick utxo */
public struct UtxoPickRequest: Codable {

    /** The address list to pick utxo from */
    public var addresses: [String]?
    /** The total amount you want to pick */
    public var amount: Int64?

    public init(addresses: [String]? = nil, amount: Int64? = nil) {
        self.addresses = addresses
        self.amount = amount
    }

}

