//
// XpubUtxo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Utxo belongs to the specified xpub */
public struct XpubUtxo: Codable {

    /** xpub of the utxo */
    public var xpub: String?
    /** Address string of this utxo */
    public var address: String?
    /** Address type, 0 for receive address, 1 for change address. path is {{addressType}}/{{addressIndex}} */
    public var addressType: Int?
    /** Address index. Address path in the xpub is {{addressType}}/{{addressIndex}} */
    public var addressIndex: Int?
    /** Txid for this utxo. */
    public var txid: String?
    /** Output index for the Utxo. */
    public var txIndex: Int?
    /** Satoshi value of the utxo. */
    public var value: Int64?
    /** The height of this utxo, -1 for unconfirmed utxo. */
    public var height: Int?
    /** The paging flag of utxo */
    public var flag: Int64?

    public init(xpub: String? = nil, address: String? = nil, addressType: Int? = nil, addressIndex: Int? = nil, txid: String? = nil, txIndex: Int? = nil, value: Int64? = nil, height: Int? = nil, flag: Int64? = nil) {
        self.xpub = xpub
        self.address = address
        self.addressType = addressType
        self.addressIndex = addressIndex
        self.txid = txid
        self.txIndex = txIndex
        self.value = value
        self.height = height
        self.flag = flag
    }

}

