//
// XpubDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Registered Xpub detail */
public struct XpubDetail: Codable {

    /** String encoded extended pubkey (xpub) */
    public var xpub: String?
    /** Next unused receive index, path /0/index */
    public var receiveIndex: Int?
    /** Max lookahead receive index. */
    public var maxReceiveIndex: Int?
    /** Next unused change index, path /1/index */
    public var changeIndex: Int?
    /** Max lookahead change index. */
    public var maxChangeIndex: Int?
    /** Current xpub process mode, 0 means preparing(not ready), 1 means synchronizing(ready) */
    public var mode: Int?
    /** Skip blocks before skipHeight while searching transactions. This will speed up sync time. */
    public var skipHeight: Int?
    /** Xpub current processed height. */
    public var processHeight: Int?

    public init(xpub: String? = nil, receiveIndex: Int? = nil, maxReceiveIndex: Int? = nil, changeIndex: Int? = nil, maxChangeIndex: Int? = nil, mode: Int? = nil, skipHeight: Int? = nil, processHeight: Int? = nil) {
        self.xpub = xpub
        self.receiveIndex = receiveIndex
        self.maxReceiveIndex = maxReceiveIndex
        self.changeIndex = changeIndex
        self.maxChangeIndex = maxChangeIndex
        self.mode = mode
        self.skipHeight = skipHeight
        self.processHeight = processHeight
    }

}

