//
// XpubResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** XpubRegister result */
public struct XpubResult: Codable {

    /** return xpub if broadcast success */
    public var xpub: String?
    /** return messages if broadcast failed */
    public var message: String?

    public init(xpub: String? = nil, message: String? = nil) {
        self.xpub = xpub
        self.message = message
    }

}

