//
// XpubRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Request object to register(or delete) a new xpub */
public struct XpubRequest: Codable {

    /** The xpub to register. */
    public var xpub: String?
    /** Skip transactions before this height. Default is 0. Ignore this while deleting xpub. */
    public var skipHeight: Int?
    /** Set the init maxReceiveIndex to {initReceiveIndex}(less than 5000) before the initial crawl , default is 200. This could increase cost. */
    public var initReceiveIndex: Int?
    /** Set the init maxChangeIndex(less than 5000) before the initial crawl , default is 200. This could increase cost. */
    public var initChangeIndex: Int?

    public init(xpub: String? = nil, skipHeight: Int? = nil, initReceiveIndex: Int? = nil, initChangeIndex: Int? = nil) {
        self.xpub = xpub
        self.skipHeight = skipHeight
        self.initReceiveIndex = initReceiveIndex
        self.initChangeIndex = initChangeIndex
    }

}

